if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(RYN_DEBUG TRUE)
elseif (CMAKE_BUILD_TYPE STREQUAL "Release")
    set(RYN_RELEASE TRUE)
else()
    message(FATAL_ERROR "Unrecognized build type")
endif()

if (WIN32)
    set(RYN_PLATFORM_WINDOWS TRUE)
elseif (LINUX)
    set(RYN_PLATFORM_LINUX TRUE)
elseif (APPLE AND UNIX)
    set(RYN_PLATFORM_MACOS TRUE)
else()
    message(FATAL_ERROR "Unsupported platform")
endif()
