if(CMAKE_BUILD_TYPE MATCHES "Debug")
    add_definitions(-DRYN_DEBUG)
else()
    add_definitions(-DRYN_RELEASE)
endif()

if(WIN32)
    add_definitions(-DRYN_PLATFORM_WINDOWS)
    set(LIBRARY_DIRECTORY "win")
elseif(APPLE)
    add_definitions(-DRYN_PLATFORM_MACOS)
    set(LIBRARY_DIRECTORY "osx")
elseif(LINUX)
    add_definitions(-DRYN_PLATFORM_LINUX)
    set(LIBRARY_DIRECTORY "linux")
else()
    message(FATAL_ERROR "Unsupported platform")
endif()

if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "amd64")
    add_definitions(-DRYN_ARCHITECTURE_X64)
    set(LIBRARY_DIRECTORY "${LIBRARY_DIRECTORY}-x64")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
    add_definitions(-DRYN_ARCHITECTURE_ARM64)
    set(LIBRARY_DIRECTORY "${LIBRARY_DIRECTORY}-arm64")
else()
    message(FATAL_ERROR, "Unsupported architecture")
endif()